language: node_js
node_js:
- '7'
script:
- npm run build
- npm test
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "PM8Sn2+WYhMDBr/okrRsOjDYjfrlvOt+FAveJ02xUyjKa0EK0uFkDraoAL40H4TN9Yhb6WYXk0oDCBJiBD2T5O+BcLO7Jw7kF8LmV84+ZmkgIJgFNAkKx47/dnHiZyb3MbdNdMJs+0KvfWdlkcueDvMJbLF69GNyPwlyAY+ngIXrnp4TXHAbPAOVs6rUzOkqB4HZI6BGKgpdsDBs49sNdspICS9pTgse/6MonZMSHvnPH9818ORPwgnVTt5DBj45K1Zi4fYxLQCZv1ETw/HAn55JW9MkR/1WpCoVP3Oac9YH2fxQEfLZEs8sediQaNOZJVt1UD4it3cdwuy5wWBME7z877saDUU+Vtu6AAH5VhTYpA80mrTFEe4V+lywybLF9vRyjK0XLCY4eZ999LAP6dtwx99XH4+pbmwZrGrj3l+t711H3PKmpN4Yf5YrJhJ2Seo7sVsKP88MVrpxrOiu5LoVXn5GMpbmQaz3MsnQCsDRvmWWJTUU/02TDL3JeP4zHWB9yaR/IybdBwyGEoMHPKC7XuX91kYlnbkFFz5v8AxpCOsFv/cKq+bcSo4kqgufOYmbhKYTeJbT0VGKB5ORAd/Nv2AbgKQVaEIY9ZSE9j4DbIpgTnaiyj3ynCOjXT4Cb2JpQOSr8S/7/leGSW8gAw7jGrvkDU2DDS0v1xeBe6k="
