language: node_js
node_js:
- '7'
script:
- npm run build
- npm test
deploy:
  skip_cleanup: true
  provider: firebase
  token: "$FIREBASE_TOKEN"
  project: predictions-3205d
env:
  global:
    secure: omvkpZCvUvnDpkDm7f2NNsjcNjYl5S0/0VnF4umb93ZWcUeX8cCCvLfVODu3a+UiqrJ4DYJl8XOYq2dxjJJ5FEC/U1USqc0TIy7haomgLhtXZQ5y8lr7b4Sk6T6VAvAKvtBNYIZOR8+w31t6m5Fcy4nrA/pDZb2+gvMj++WN80IB58RUCuPklf82xVP+YwwHPBrgd8BL8YrS8jbu6Awas/d4zYhEQD7qI4uqHXE8tfEtvoJzDciXu2MjMl4SJuJKTW+2vb4JosIE3KYTDSQ5oqlDoJ0O2CyllJRE8D4wWW4260LajIKna/ijlSpAjEyVX3Ut5fjBtxqHxh5GGYOwVhHw+72wyJ6reLJbeqE+MB+eGrnksHTEvP3Te0OMKD6rxq0hP0SzZQa7U6Pbd9jahVT2CrGaCiEH4e2E97cnjZz2/g01wsnIIO8VFQ1/T9nioyFtQzr6rdUxPk7aJD/dZXAeHlvJro1TpvIOZ2YiB4h6/gwYltmxNkQA+Ptyb7RQulXxLYLlUSHSlayip7uctTXLmsjeB2V5N2E/jVVwATcOcAtoFBoH7vjuicA1UXgaYvVHfGSEpKUJAcFSyQfTfMt7rFN0ieItcJbGg5PNdUcCGmDj/O89fwdTRwbZwZJri2BEI0s4N+6KqkbUaj91sTGJ3Fk2g2+tUXdSHydYG9s=
