language: node_js
node_js:
- '7'

script: 
- npm run build
- npm test

deploy:
  provider: firebase
  token:
    secure: "ajHRsVLVyASsIBuSu1aP/j3KaOM9fMwJ44YyPcdQPdhJ/9yP7U/ssYlTy84p63Q2z+cYIN+jOJeJ/wU73HLBwPrPCZTcfpSFegk0dL6qAeT9azRkCYK/tp1Q0MH90po3kDOHOI155Z1yBK4q9CpJTb8pFoahT56dZz+hJedMmJjkrrBmrSXe79YAhYlkyPs5BuU5LwmfqRD5+LPIoYvTNSqBXbOlrARWPZTze3UD4ASGSGDpN5R4bQvzvtYCSdFYOifszt5Y4L+BnDGZPT41muH8eVKsNu0bCN9UyGn+5I/IqrX1jgvma2B9l6mcNhHHSYWAqSpQwZaXzbU6FRoWXXh4sQHQIcjXcaOckUzT0cLnmZYg2bMVz7oqr0kdzNwlWZaKJAXiCcIJTj0dwbKuoRt8M2HsBvDZo9ZV/Cu8jheWcIjfmzHop4W6y5Hj6mp6wLE3vf51jHlHuoPw1ZE3WwZ6Lxbfc4W5/nzUQ05t3qMvKdX6UH7knvfRkjOJyufHt4PtdWuUzMzElvJuLlGp/3cY5FjrWSKO6NnPXeoZaLbfA7PRU++Ck97jeEytUv9q6SWCoFh8UgXiL7nbcsJnHlcubJJ/hf8b6d0uTTw+ATL58fXYIKtvh9v7EQgl7Ytcoq6RJnaYAleGUZbTcIyi1QxuxSyrthdqvHBlc9tqxps="
